### PR TITLE
Support add, update, delete, read alarm clocks

### LINKED ISSUE #6: Support for Squeezebox alarms?
Moving from FHEM to Home Assistant I found that HA's support for Squeezeboxes is incomplete when it comes to their alarm clock functionality. Maybe one could try to work around it using call_query on the LMS server entity, but having the alarm clock data in the player's attributes (or something similar, I am not fully sure of what the proper HA way to do it would be) seems more convenient. So the question is, if I, in a first step, come up with a PR for this library, would you be willing to have a look at it? If yes, I'd try, if not, fair enough, then I'd probably go the pyscript way for my own HA instance or something similar.

### PR DESCRIPTION
**Pull request by wollew**
Initial implementation of alarms support. I tested all method calls with my own installation of LMS, no automated tests, though. I've never implemented a HA integration, so I am not sure how useful this kind of interface is for the Squeezebox Ha integration, let me know if I you want me to change something. 

Closes #6.

### CODE REVIEW

**Comment by wollew** [comment]
Also, you can probably see that Python is not my "native language", so please excuse any non-idiomatic use of Python, feel free to fix :-)

**Comment by rajlaud** [comment]
Thanks @wollew. Looks good. I'm going to merge and add some tests.

**Comment by wollew** [comment]
Sounds good to me. How do you suggest we proceed to get this functionality into HA? I can try to also create a PR for the squeezebox integration, not sure how long it takes to setup a dev environment for that.

**Comment by rajlaud** [comment]
I'm happy to do the PR for Home Assistant. It will probably be sometime next week

**Comment by wollew** [comment]
Hi, now that 2024.10 has been releases, any chance you'll soon finde the time to integrate alarm clock support in HA?

**Comment by rajlaud** [comment]
Yes! I started on this and got pulled away by another part of the integration. Returning to it now.

**Pull request merged**
